version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:20.04
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo "Hello, World!"
            ls -al
            ./test.sh