version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/ubuntu-dev:20.04
    steps:
      - checkout
      - run:
          name: install clang
          command: |
            apk update
            apk add clang
      - run:
          name: Test
          command: |
            ./test.sh